[package]
name = "database"
version = "0.1.0"
authors = ["Kai <cnaicc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neo4rs = "0.5.8"
tokio = { version = "1", features = ["full"] }
