[package]
name = "tools"
version = "0.1.0"
authors = ["Kai <cnaicc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_derive = "^1.0.8"
serde = "^1.0.8"
dotenv = "0.15.0"
config = "0.11.0"
